max_steps: 60_000
save_iterations: [30_000, 60_000]
output: outputs/mc_street
name: coarse

data:
  path: data/MatrixCity/street
  parser:
    class_path: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap
    init_args:
      split_mode: experiment
      eval_image_select_mode: list
      eval_list: data/MatrixCity/street/val_images.txt
  train_max_num_images_to_cache: 256
  num_workers: 6
  async_caching: true

model:
  background_color: [1.0, 1.0, 1.0]
  renderer_output_types: [rgb, depth, normal]
  gaussian:
    class_path: internal.models.vanilla_gaussian.VanillaGaussian
    init_args:
      optimization:
        scales_lr: 1e-3
        means_lr_init: 1.6e-5
        means_lr_scheduler:
          lr_final: 1.6e-6
          max_steps: 60_000
  renderer:
    class_path: surf_recon.modeling.renderers.RaDeGSRenderer
  metric:
    class_path: surf_recon.modeling.metrics.InvDepthRegularizedMetrics
  density:
    class_path: surf_recon.modeling.density_controllers.TrimDensityController
    init_args:
      densify_grad_threshold: 2e-5
      densify_from_iter: 4_000
      densification_interval: 500
      opacity_reset_interval: 60_000
      densify_until_iter: 30_000
      trim_from_iter: 8_000
      trim_interval: 10_000
      trim_ratio: 0.05
