max_steps: 30_000
save_iterations: [15_000, 30_000]
output: outputs/smbu
name: coarse

data:
  path: data/GauU_Scene/SMBU
  parser:
    class_path: surf_recon.modeling.block_colmap_parser.BlockDepthColmap
    init_args:
      split_mode: experiment
      eval_image_select_mode: list
      eval_list: data/GauU_Scene/SMBU/val_images.txt
  train_max_num_images_to_cache: -1
  num_workers: 6
  async_caching: true

model:
  renderer_output_types: [rgb, depth, normal]
  gaussian:
    class_path: internal.models.vanilla_gaussian.VanillaGaussian
    init_args:
      optimization:
        means_lr_init: 6.4e-5
        means_lr_scheduler:
          lr_final: 6.4e-7
          max_steps: 30_000
  renderer:
    class_path: surf_recon.modeling.renderers.RaDeGSRenderer
  metric:
    class_path: surf_recon.modeling.metrics.DepthRegularizedMetrics
    init_args:
      dn_from_iter: 7_000
      depth_loss_weight:
        init: 0.5
  density:
    class_path: surf_recon.modeling.density_controllers.TrimDensityController
    init_args:
      densification_interval: 200