max_steps: 60_000
save_iterations: [30_000, 60_000]
output: outputs/mc_aerial
name: coarse

data:
  path: data/MatrixCity/aerial
  parser:
    class_path: surf_recon.modeling.block_colmap_parser.BlockDepthColmap
    init_args:
      split_mode: experiment
      eval_image_select_mode: list
      eval_list: data/MatrixCity/aerial/val_images.txt
  train_max_num_images_to_cache: 64
  num_workers: 6
  async_caching: true

model:
  # background_color: [0.25, 0.25, 0.25]
  renderer_output_types: [rgb, depth, normal]
  gaussian:
    class_path: internal.models.vanilla_gaussian.VanillaGaussian
    init_args:
      optimization:
        means_lr_init: 6.4e-5
        means_lr_scheduler:
          lr_final: 6.4e-7
          max_steps: 60_000
  renderer:
    class_path: surf_recon.modeling.renderers.RaDeGSRenderer
  metric:
    class_path: surf_recon.modeling.metrics.DepthRegularizedMetrics
    init_args:
      dn_from_iter: 15_000
      depth_loss_weight:
        init: 0.5
  density:
    class_path: surf_recon.modeling.density_controllers.TrimDensityController
    init_args:
      densification_interval: 1000
      opacity_reset_interval: 6000
      densify_until_iter: 30_000
      trim_interval: 3000
      trim_ratio: 0.05
